FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Generate swagger docs or run typescript build if necessary
# RUN npm run build

EXPOSE 8000

CMD ["npm", "start"]
